version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command: --config.file="/etc/prometheus/prometheus.yaml"

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - /:/hostfs
    command: --path.rootfs=/hostfs

  pushprox-proxy:
    image: jonascheng/pushprox
    ports:
      - 80:8080
