# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.
scrape_configs:
  # Scrape Prometheus itself every 10 seconds.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'pushprox-proxy'
    proxy_url: http://pushprox-proxy:8080/
    static_configs:
      - targets: ['vagrant.vm:30091', 'vagrant.vm:30080']

  # - job_name: 'node-exporter-edge'
  #   scrape_interval: 10s
  #   static_configs:
  #     # host ip ifconfig en0
  #     - targets: ['192.168.1.109:30091']
